export interface Category {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  color: string;
  subCategories?: Category[];
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  price: number;
  weight: string;
  shelfLife: string;
  ingredients: string;
  description: string;
  emoji: string;
  badge: string | null;
  rating: number;
  reviews: number;
  customizable: boolean;
  images?: string[];
  stock?: number;
  originalPrice?: number;
  benefits?: string[];
  isPopular?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  sku?: string;
}

export const categories: Category[] = [
  { id: "biriyani-kit", name: "Biriyani Kit", slug: "biriyani-kit", emoji: "🍛", color: "bg-amber-100" },
  { id: "ghee-rice-combo-kit", name: "Ghee Rice", slug: "ghee-rice-combo-kit", emoji: "🍚", color: "bg-yellow-100" },
  { 
    id: "pickles", name: "Pickles", slug: "pickles", emoji: "🥒", color: "bg-green-100",
    subCategories: [
      { id: "pickles-150g", name: "150g", slug: "pickles-150g", emoji: "🥒", color: "bg-green-50" },
      { id: "pickles-300g", name: "300g", slug: "pickles-300g", emoji: "🥒", color: "bg-green-50" },
      { id: "pickles-500g", name: "500g", slug: "pickles-500g", emoji: "🥒", color: "bg-green-50" },
      { id: "pickles-1kg", name: "1kg", slug: "pickles-1kg", emoji: "🥒", color: "bg-green-50" },
    ]
  },
  { id: "seenima", name: "Seenima", slug: "seenima", emoji: "🫙", color: "bg-orange-100" },
  { 
    id: "sambals", name: "Sambals", slug: "sambals", emoji: "🌶️", color: "bg-red-100",
    subCategories: [
      { id: "sambal-70g", name: "Sambal 70g", slug: "sambal-70g", emoji: "🌶️", color: "bg-red-50" },
      { id: "sambal-100g", name: "Sambal 100g", slug: "sambal-100g", emoji: "🌶️", color: "bg-red-50" },
      { id: "sambal-250g", name: "Sambal 250g", slug: "sambal-250g", emoji: "🌶️", color: "bg-red-50" },
      { id: "sambal-500g", name: "Sambal 500g", slug: "sambal-500g", emoji: "🌶️", color: "bg-red-50" },
      { id: "sambal-1kg", name: "Sambal 1kg", slug: "sambal-1kg", emoji: "🌶️", color: "bg-red-50" },
    ]
  },
  { id: "food-truck-list", name: "Food Truck List", slug: "food-truck-list", emoji: "🚚", color: "bg-indigo-100" },
  { id: "custom-orders", name: "Custom Orders", slug: "custom-orders", emoji: "✨", color: "bg-teal-100" },
];

export const products: Product[] = [
  {
    "id": "biriyani-combo-kit",
    "name": "Biriyani Combo Kit",
    "slug": "biriyani-combo-kit",
    "category": "biriyani-kit",
    "price": 1400,
    "weight": "500g",
    "shelfLife": "3 months",
    "ingredients": "Basmati rice spice blend, dried herbs, whole spices (cinnamon, cardamom, cloves), natural salt",
    "description": "Our signature Biriyani Combo Kit brings the authentic flavour of Sri Lankan biriyani to your home. Packed with hand-selected whole spices and a carefully blended masala, this kit makes cooking perfect biriyani effortless. Simply follow our included recipe card for restaurant-quality results every time.",
    "emoji": "🍛",
    "badge": "Best Seller",
    "rating": 4.9,
    "reviews": 120,
    "customizable": false
  },
  {
    "id": "ghee-rice-combo-kit",
    "name": "Ghee Rice Combo Kit",
    "slug": "ghee-rice-combo-kit",
    "category": "ghee-rice-combo-kit",
    "price": 1350,
    "weight": "500g",
    "shelfLife": "3 months",
    "ingredients": "Premium short-grain rice, pure ghee, cardamom, cloves, bay leaves, roasted cashews, raisins",
    "description": "Indulge in the aromatic goodness of traditional Ghee Rice. This kit provides everything you need to prepare fluffy, flavorful ghee rice, loaded with the richest spices, pure cow ghee, and a crunchy topping of cashews and raisins.",
    "emoji": "🍚",
    "badge": "Best Seller",
    "rating": 4.8,
    "reviews": 87,
    "customizable": false
  },
  {
    "id": "seenima-200g",
    "name": "Seenima 200g",
    "slug": "seenima-200g",
    "category": "seenima",
    "price": 380,
    "weight": "200g",
    "shelfLife": "6 months",
    "ingredients": "Seenima leaves, cardamom, cloves, onions, chili flakes, sugar, salt, oil",
    "description": "A sweet and spicy onion relish caramelized to perfection with Sri Lankan spices. Rich, fragrant, and highly versatile.",
    "emoji": "🫙",
    "badge": null,
    "rating": 4.6,
    "reviews": 38,
    "customizable": true
  },
  {
    "id": "seenima-300g",
    "name": "Seenima 300g",
    "slug": "seenima-300g",
    "category": "seenima",
    "price": 500,
    "weight": "300g",
    "shelfLife": "6 months",
    "ingredients": "Seenima leaves, cardamom, cloves, onions, chili flakes, sugar, salt, oil",
    "description": "A sweet and spicy onion relish caramelized to perfection with Sri Lankan spices. Rich, fragrant, and highly versatile.",
    "emoji": "🫙",
    "badge": null,
    "rating": 4.6,
    "reviews": 38,
    "customizable": true
  },
  {
    "id": "seenima-500g",
    "name": "Seenima 500g",
    "slug": "seenima-500g",
    "category": "seenima",
    "price": 880,
    "weight": "500g",
    "shelfLife": "6 months",
    "ingredients": "Seenima leaves, cardamom, cloves, onions, chili flakes, sugar, salt, oil",
    "description": "A sweet and spicy onion relish caramelized to perfection with Sri Lankan spices. Rich, fragrant, and highly versatile.",
    "emoji": "🫙",
    "badge": null,
    "rating": 4.6,
    "reviews": 38,
    "customizable": true
  },
  {
    "id": "seenima-1kg",
    "name": "Seenima 1kg",
    "slug": "seenima-1kg",
    "category": "seenima",
    "price": 1760,
    "weight": "1kg",
    "shelfLife": "6 months",
    "ingredients": "Seenima leaves, cardamom, cloves, onions, chili flakes, sugar, salt, oil",
    "description": "A sweet and spicy onion relish caramelized to perfection with Sri Lankan spices. Rich, fragrant, and highly versatile.",
    "emoji": "🫙",
    "badge": null,
    "rating": 4.6,
    "reviews": 38,
    "customizable": true
  },
  {
    "id": "beef-pickle-150g",
    "name": "Beef Pickle 150g",
    "slug": "beef-pickle-150g",
    "category": "pickles-150g",
    "price": 700,
    "weight": "150g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Our homemade Beef Pickle is slow-cured with authentic Sri Lankan spices and vinegar.",
    "emoji": "🥩",
    "badge": "Popular",
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "beef-pickle-300g",
    "name": "Beef Pickle 300g",
    "slug": "beef-pickle-300g",
    "category": "pickles-300g",
    "price": 1350,
    "weight": "300g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Our homemade Beef Pickle is slow-cured with authentic Sri Lankan spices and vinegar.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "beef-pickle-500g",
    "name": "Beef Pickle 500g",
    "slug": "beef-pickle-500g",
    "category": "pickles-500g",
    "price": 2700,
    "weight": "500g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Our homemade Beef Pickle is slow-cured with authentic Sri Lankan spices and vinegar.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "beef-pickle-1kg",
    "name": "Beef Pickle 1kg",
    "slug": "beef-pickle-1kg",
    "category": "pickles-1kg",
    "price": 5400,
    "weight": "1kg",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Our homemade Beef Pickle is slow-cured with authentic Sri Lankan spices and vinegar.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "chicken-pickle-150g",
    "name": "Chicken Pickle 150g",
    "slug": "chicken-pickle-150g",
    "category": "pickles-150g",
    "price": 700,
    "weight": "150g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy, spicy, and packed with authentic Sri Lankan flavour — our homemade Chicken Pickle.",
    "emoji": "🐔",
    "badge": "Popular",
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "chicken-pickle-300g",
    "name": "Chicken Pickle 300g",
    "slug": "chicken-pickle-300g",
    "category": "pickles-300g",
    "price": 1350,
    "weight": "300g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy, spicy, and packed with authentic Sri Lankan flavour — our homemade Chicken Pickle.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "chicken-pickle-500g",
    "name": "Chicken Pickle 500g",
    "slug": "chicken-pickle-500g",
    "category": "pickles-500g",
    "price": 2700,
    "weight": "500g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy, spicy, and packed with authentic Sri Lankan flavour — our homemade Chicken Pickle.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "chicken-pickle-1kg",
    "name": "Chicken Pickle 1kg",
    "slug": "chicken-pickle-1kg",
    "category": "pickles-1kg",
    "price": 5400,
    "weight": "1kg",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy, spicy, and packed with authentic Sri Lankan flavour — our homemade Chicken Pickle.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "baabath-pickle-150g",
    "name": "Baabath Pickle 150g",
    "slug": "baabath-pickle-150g",
    "category": "pickles-150g",
    "price": 700,
    "weight": "150g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional tripe pickle, intensely flavoured with local spices and vinegar.",
    "emoji": "🥘",
    "badge": "Popular",
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "baabath-pickle-300g",
    "name": "Baabath Pickle 300g",
    "slug": "baabath-pickle-300g",
    "category": "pickles-300g",
    "price": 1350,
    "weight": "300g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional tripe pickle, intensely flavoured with local spices and vinegar.",
    "emoji": "🥘",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "baabath-pickle-500g",
    "name": "Baabath Pickle 500g",
    "slug": "baabath-pickle-500g",
    "category": "pickles-500g",
    "price": 2700,
    "weight": "500g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional tripe pickle, intensely flavoured with local spices and vinegar.",
    "emoji": "🥘",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "baabath-pickle-1kg",
    "name": "Baabath Pickle 1kg",
    "slug": "baabath-pickle-1kg",
    "category": "pickles-1kg",
    "price": 5400,
    "weight": "1kg",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional tripe pickle, intensely flavoured with local spices and vinegar.",
    "emoji": "🥘",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "prawns-pickle-150g",
    "name": "Prawns Pickle 150g",
    "slug": "prawns-pickle-150g",
    "category": "pickles-150g",
    "price": 700,
    "weight": "150g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy and spice-kissed prawns pickle, handmade with the freshest local catch.",
    "emoji": "🦐",
    "badge": "Popular",
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "prawns-pickle-300g",
    "name": "Prawns Pickle 300g",
    "slug": "prawns-pickle-300g",
    "category": "pickles-300g",
    "price": 1350,
    "weight": "300g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy and spice-kissed prawns pickle, handmade with the freshest local catch.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "prawns-pickle-500g",
    "name": "Prawns Pickle 500g",
    "slug": "prawns-pickle-500g",
    "category": "pickles-500g",
    "price": 2700,
    "weight": "500g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy and spice-kissed prawns pickle, handmade with the freshest local catch.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "prawns-pickle-1kg",
    "name": "Prawns Pickle 1kg",
    "slug": "prawns-pickle-1kg",
    "category": "pickles-1kg",
    "price": 5400,
    "weight": "1kg",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Tangy and spice-kissed prawns pickle, handmade with the freshest local catch.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "crab-pickle-150g",
    "name": "Crab Pickle 150g",
    "slug": "crab-pickle-150g",
    "category": "pickles-150g",
    "price": 650,
    "weight": "150g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "A rare and luxurious pickle made from fresh crab meat, slow-cooked in a spicy tamarind base.",
    "emoji": "🦀",
    "badge": "Popular",
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "crab-pickle-300g",
    "name": "Crab Pickle 300g",
    "slug": "crab-pickle-300g",
    "category": "pickles-300g",
    "price": 1250,
    "weight": "300g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "A rare and luxurious pickle made from fresh crab meat, slow-cooked in a spicy tamarind base.",
    "emoji": "🦀",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "crab-pickle-500g",
    "name": "Crab Pickle 500g",
    "slug": "crab-pickle-500g",
    "category": "pickles-500g",
    "price": 2500,
    "weight": "500g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "A rare and luxurious pickle made from fresh crab meat, slow-cooked in a spicy tamarind base.",
    "emoji": "🦀",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "crab-pickle-1kg",
    "name": "Crab Pickle 1kg",
    "slug": "crab-pickle-1kg",
    "category": "pickles-1kg",
    "price": 5000,
    "weight": "1kg",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "A rare and luxurious pickle made from fresh crab meat, slow-cooked in a spicy tamarind base.",
    "emoji": "🦀",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "fish-pickle-150g",
    "name": "Fish Pickle 150g",
    "slug": "fish-pickle-150g",
    "category": "pickles-150g",
    "price": 650,
    "weight": "150g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional Sri Lankan fish pickle made from fresh tuna cubes, cured with goraka and black pepper.",
    "emoji": "🐟",
    "badge": "Popular",
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "fish-pickle-300g",
    "name": "Fish Pickle 300g",
    "slug": "fish-pickle-300g",
    "category": "pickles-300g",
    "price": 1250,
    "weight": "300g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional Sri Lankan fish pickle made from fresh tuna cubes, cured with goraka and black pepper.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "fish-pickle-500g",
    "name": "Fish Pickle 500g",
    "slug": "fish-pickle-500g",
    "category": "pickles-500g",
    "price": 2500,
    "weight": "500g",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional Sri Lankan fish pickle made from fresh tuna cubes, cured with goraka and black pepper.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "fish-pickle-1kg",
    "name": "Fish Pickle 1kg",
    "slug": "fish-pickle-1kg",
    "category": "pickles-1kg",
    "price": 5000,
    "weight": "1kg",
    "shelfLife": "6 months",
    "ingredients": "Secret spices, vinegar, oil",
    "description": "Traditional Sri Lankan fish pickle made from fresh tuna cubes, cured with goraka and black pepper.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.8,
    "reviews": 50,
    "customizable": true
  },
  {
    "id": "beef-sambal-70g",
    "name": "Beef Sambal 70g",
    "slug": "beef-sambal-70g",
    "category": "sambal-70g",
    "price": 380,
    "weight": "70g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A dry, textured sambal featuring savory shredded beef pan-fried with caramelized onions and hot chili flakes.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "beef-sambal-100g",
    "name": "Beef Sambal 100g",
    "slug": "beef-sambal-100g",
    "category": "sambal-100g",
    "price": 540,
    "weight": "100g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A dry, textured sambal featuring savory shredded beef pan-fried with caramelized onions and hot chili flakes.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "beef-sambal-250g",
    "name": "Beef Sambal 250g",
    "slug": "beef-sambal-250g",
    "category": "sambal-250g",
    "price": 1350,
    "weight": "250g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A dry, textured sambal featuring savory shredded beef pan-fried with caramelized onions and hot chili flakes.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "beef-sambal-500g",
    "name": "Beef Sambal 500g",
    "slug": "beef-sambal-500g",
    "category": "sambal-500g",
    "price": 2700,
    "weight": "500g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A dry, textured sambal featuring savory shredded beef pan-fried with caramelized onions and hot chili flakes.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "beef-sambal-1kg",
    "name": "Beef Sambal 1kg",
    "slug": "beef-sambal-1kg",
    "category": "sambal-1kg",
    "price": 4700,
    "weight": "1kg",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A dry, textured sambal featuring savory shredded beef pan-fried with caramelized onions and hot chili flakes.",
    "emoji": "🥩",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "chicken-sambal-70g",
    "name": "Chicken Sambal 70g",
    "slug": "chicken-sambal-70g",
    "category": "sambal-70g",
    "price": 350,
    "weight": "70g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rich, flavour-packed sambal made with tender chicken and our special chili blend.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "chicken-sambal-100g",
    "name": "Chicken Sambal 100g",
    "slug": "chicken-sambal-100g",
    "category": "sambal-100g",
    "price": 500,
    "weight": "100g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rich, flavour-packed sambal made with tender chicken and our special chili blend.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "chicken-sambal-250g",
    "name": "Chicken Sambal 250g",
    "slug": "chicken-sambal-250g",
    "category": "sambal-250g",
    "price": 1250,
    "weight": "250g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rich, flavour-packed sambal made with tender chicken and our special chili blend.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "chicken-sambal-500g",
    "name": "Chicken Sambal 500g",
    "slug": "chicken-sambal-500g",
    "category": "sambal-500g",
    "price": 2500,
    "weight": "500g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rich, flavour-packed sambal made with tender chicken and our special chili blend.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "chicken-sambal-1kg",
    "name": "Chicken Sambal 1kg",
    "slug": "chicken-sambal-1kg",
    "category": "sambal-1kg",
    "price": 4300,
    "weight": "1kg",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rich, flavour-packed sambal made with tender chicken and our special chili blend.",
    "emoji": "🐔",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "maldive-fish-sambal-70g",
    "name": "Maldive Fish Sambal 70g",
    "slug": "maldive-fish-sambal-70g",
    "category": "sambal-70g",
    "price": 350,
    "weight": "70g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Traditional Sri Lankan Umbalakada Sambal. Thick, spicy onion-relish loaded with Maldive fish chips.",
    "emoji": "🐠",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "maldive-fish-sambal-100g",
    "name": "Maldive Fish Sambal 100g",
    "slug": "maldive-fish-sambal-100g",
    "category": "sambal-100g",
    "price": 500,
    "weight": "100g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Traditional Sri Lankan Umbalakada Sambal. Thick, spicy onion-relish loaded with Maldive fish chips.",
    "emoji": "🐠",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "maldive-fish-sambal-250g",
    "name": "Maldive Fish Sambal 250g",
    "slug": "maldive-fish-sambal-250g",
    "category": "sambal-250g",
    "price": 1250,
    "weight": "250g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Traditional Sri Lankan Umbalakada Sambal. Thick, spicy onion-relish loaded with Maldive fish chips.",
    "emoji": "🐠",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "maldive-fish-sambal-500g",
    "name": "Maldive Fish Sambal 500g",
    "slug": "maldive-fish-sambal-500g",
    "category": "sambal-500g",
    "price": 2500,
    "weight": "500g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Traditional Sri Lankan Umbalakada Sambal. Thick, spicy onion-relish loaded with Maldive fish chips.",
    "emoji": "🐠",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "maldive-fish-sambal-1kg",
    "name": "Maldive Fish Sambal 1kg",
    "slug": "maldive-fish-sambal-1kg",
    "category": "sambal-1kg",
    "price": 4300,
    "weight": "1kg",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Traditional Sri Lankan Umbalakada Sambal. Thick, spicy onion-relish loaded with Maldive fish chips.",
    "emoji": "🐠",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "kooni-sambal-70g",
    "name": "Prawns Sambal 70g",
    "slug": "kooni-sambal-70g",
    "category": "sambal-70g",
    "price": 350,
    "weight": "70g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Classic Sri Lankan Kooni Sambal. Sun-dried small shrimp toasted and ground with onions, red chili, and fresh lime.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "kooni-sambal-100g",
    "name": "Prawns Sambal 100g",
    "slug": "kooni-sambal-100g",
    "category": "sambal-100g",
    "price": 500,
    "weight": "100g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Classic Sri Lankan Kooni Sambal. Sun-dried small shrimp toasted and ground with onions, red chili, and fresh lime.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "kooni-sambal-250g",
    "name": "Prawns Sambal 250g",
    "slug": "kooni-sambal-250g",
    "category": "sambal-250g",
    "price": 1250,
    "weight": "250g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Classic Sri Lankan Kooni Sambal. Sun-dried small shrimp toasted and ground with onions, red chili, and fresh lime.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "kooni-sambal-500g",
    "name": "Prawns Sambal 500g",
    "slug": "kooni-sambal-500g",
    "category": "sambal-500g",
    "price": 2500,
    "weight": "500g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Classic Sri Lankan Kooni Sambal. Sun-dried small shrimp toasted and ground with onions, red chili, and fresh lime.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "kooni-sambal-1kg",
    "name": "Prawns Sambal 1kg",
    "slug": "kooni-sambal-1kg",
    "category": "sambal-1kg",
    "price": 4300,
    "weight": "1kg",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Classic Sri Lankan Kooni Sambal. Sun-dried small shrimp toasted and ground with onions, red chili, and fresh lime.",
    "emoji": "🦐",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "dry-fish-sambal-70g",
    "name": "Dry Fish Sambal 70g",
    "slug": "dry-fish-sambal-70g",
    "category": "sambal-70g",
    "price": 350,
    "weight": "70g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Made from premium dried tuna — crispy, salty, spicy, and tangy.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "dry-fish-sambal-100g",
    "name": "Dry Fish Sambal 100g",
    "slug": "dry-fish-sambal-100g",
    "category": "sambal-100g",
    "price": 500,
    "weight": "100g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Made from premium dried tuna — crispy, salty, spicy, and tangy.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "dry-fish-sambal-250g",
    "name": "Dry Fish Sambal 250g",
    "slug": "dry-fish-sambal-250g",
    "category": "sambal-250g",
    "price": 1250,
    "weight": "250g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Made from premium dried tuna — crispy, salty, spicy, and tangy.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "dry-fish-sambal-500g",
    "name": "Dry Fish Sambal 500g",
    "slug": "dry-fish-sambal-500g",
    "category": "sambal-500g",
    "price": 2500,
    "weight": "500g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Made from premium dried tuna — crispy, salty, spicy, and tangy.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "dry-fish-sambal-1kg",
    "name": "Dry Fish Sambal 1kg",
    "slug": "dry-fish-sambal-1kg",
    "category": "sambal-1kg",
    "price": 4300,
    "weight": "1kg",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "Made from premium dried tuna — crispy, salty, spicy, and tangy.",
    "emoji": "🐟",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "banana-blossom-sambal-70g",
    "name": "Banana Blossom Sambal 70g",
    "slug": "banana-blossom-sambal-70g",
    "category": "sambal-70g",
    "price": 280,
    "weight": "70g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rare vegetarian-friendly delicacy. Finely shredded banana blossoms tempered with spices, curry leaves, and lime.",
    "emoji": "🌸",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "banana-blossom-sambal-100g",
    "name": "Banana Blossom Sambal 100g",
    "slug": "banana-blossom-sambal-100g",
    "category": "sambal-100g",
    "price": 400,
    "weight": "100g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rare vegetarian-friendly delicacy. Finely shredded banana blossoms tempered with spices, curry leaves, and lime.",
    "emoji": "🌸",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "banana-blossom-sambal-250g",
    "name": "Banana Blossom Sambal 250g",
    "slug": "banana-blossom-sambal-250g",
    "category": "sambal-250g",
    "price": 1000,
    "weight": "250g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rare vegetarian-friendly delicacy. Finely shredded banana blossoms tempered with spices, curry leaves, and lime.",
    "emoji": "🌸",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "banana-blossom-sambal-500g",
    "name": "Banana Blossom Sambal 500g",
    "slug": "banana-blossom-sambal-500g",
    "category": "sambal-500g",
    "price": 2000,
    "weight": "500g",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rare vegetarian-friendly delicacy. Finely shredded banana blossoms tempered with spices, curry leaves, and lime.",
    "emoji": "🌸",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  },
  {
    "id": "banana-blossom-sambal-1kg",
    "name": "Banana Blossom Sambal 1kg",
    "slug": "banana-blossom-sambal-1kg",
    "category": "sambal-1kg",
    "price": 3300,
    "weight": "1kg",
    "shelfLife": "4 months",
    "ingredients": "Onion, chili, spices, oil",
    "description": "A rare vegetarian-friendly delicacy. Finely shredded banana blossoms tempered with spices, curry leaves, and lime.",
    "emoji": "🌸",
    "badge": null,
    "rating": 4.7,
    "reviews": 60,
    "customizable": true
  }
];
